# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_admin.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1246, 936)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: white;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #66e, stop: 1 #bbf);\n"
"background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #bbf, stop: 1 #55f);\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #eee, stop:1 #ccc);\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: white;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #66e, stop: 1 #bbf);\n"
"background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #bbf, stop: 1 #55f);\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #eee, stop:1 #ccc);\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("font:12pt \"Segoe UI\";")
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 321, 855))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pb_reset_img = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pb_reset_img.setStyleSheet("background-color: rgb(175, 236, 255);\n"
"color: rgb(255, 0, 127);\n"
"")
        self.pb_reset_img.setObjectName("pb_reset_img")
        self.gridLayout_13.addWidget(self.pb_reset_img, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_13, 1, 0, 1, 1)
        self.toolBox = QtWidgets.QToolBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 368, 331))
        self.page.setObjectName("page")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.frame_7 = QtWidgets.QFrame(self.page)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.sb_zrange1 = QtWidgets.QSpinBox(self.frame_7)
        self.sb_zrange1.setMinimum(0)
        self.sb_zrange1.setMaximum(500)
        self.sb_zrange1.setProperty("value", 0)
        self.sb_zrange1.setDisplayIntegerBase(10)
        self.sb_zrange1.setObjectName("sb_zrange1")
        self.gridLayout_17.addWidget(self.sb_zrange1, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_17.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_17.addWidget(self.label_9, 2, 2, 1, 1)
        self.sb_yrange2 = QtWidgets.QSpinBox(self.frame_7)
        self.sb_yrange2.setReadOnly(False)
        self.sb_yrange2.setMinimum(1)
        self.sb_yrange2.setMaximum(10000)
        self.sb_yrange2.setProperty("value", 100)
        self.sb_yrange2.setObjectName("sb_yrange2")
        self.gridLayout_17.addWidget(self.sb_yrange2, 2, 3, 1, 1)
        self.sb_zrange2 = QtWidgets.QSpinBox(self.frame_7)
        self.sb_zrange2.setMinimum(1)
        self.sb_zrange2.setMaximum(5000)
        self.sb_zrange2.setProperty("value", 1200)
        self.sb_zrange2.setDisplayIntegerBase(10)
        self.sb_zrange2.setObjectName("sb_zrange2")
        self.gridLayout_17.addWidget(self.sb_zrange2, 0, 3, 1, 1)
        self.sb_xrange1 = QtWidgets.QSpinBox(self.frame_7)
        self.sb_xrange1.setReadOnly(False)
        self.sb_xrange1.setMinimum(0)
        self.sb_xrange1.setMaximum(10000)
        self.sb_xrange1.setProperty("value", 0)
        self.sb_xrange1.setObjectName("sb_xrange1")
        self.gridLayout_17.addWidget(self.sb_xrange1, 1, 1, 1, 1)
        self.sb_xrange2 = QtWidgets.QSpinBox(self.frame_7)
        self.sb_xrange2.setReadOnly(False)
        self.sb_xrange2.setMinimum(1)
        self.sb_xrange2.setMaximum(10000)
        self.sb_xrange2.setProperty("value", 100)
        self.sb_xrange2.setObjectName("sb_xrange2")
        self.gridLayout_17.addWidget(self.sb_xrange2, 1, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_7)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_17.addWidget(self.label_22, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_7)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_17.addWidget(self.label_19, 1, 0, 1, 1)
        self.sb_yrange1 = QtWidgets.QSpinBox(self.frame_7)
        self.sb_yrange1.setReadOnly(False)
        self.sb_yrange1.setMinimum(0)
        self.sb_yrange1.setMaximum(10000)
        self.sb_yrange1.setProperty("value", 0)
        self.sb_yrange1.setObjectName("sb_yrange1")
        self.gridLayout_17.addWidget(self.sb_yrange1, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_7)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_17.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_7)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_17.addWidget(self.label_20, 0, 0, 1, 1)
        self.gridLayout_30.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.pb_crop = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_crop.sizePolicy().hasHeightForWidth())
        self.pb_crop.setSizePolicy(sizePolicy)
        self.pb_crop.setStyleSheet("background-color: rgb(175, 236, 255);\n"
"color: rgb(255, 0, 127);\n"
"")
        self.pb_crop.setObjectName("pb_crop")
        self.gridLayout_30.addWidget(self.pb_crop, 1, 0, 1, 1)
        self.gridLayout_31.addWidget(self.frame_7, 1, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.page)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cb_rebin = QtWidgets.QCheckBox(self.frame_6)
        self.cb_rebin.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_rebin.sizePolicy().hasHeightForWidth())
        self.cb_rebin.setSizePolicy(sizePolicy)
        self.cb_rebin.setObjectName("cb_rebin")
        self.horizontalLayout_9.addWidget(self.cb_rebin)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.cb_upscale = QtWidgets.QCheckBox(self.frame_6)
        self.cb_upscale.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_upscale.sizePolicy().hasHeightForWidth())
        self.cb_upscale.setSizePolicy(sizePolicy)
        self.cb_upscale.setObjectName("cb_upscale")
        self.horizontalLayout_10.addWidget(self.cb_upscale)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.sb_scaling_factor = QtWidgets.QSpinBox(self.frame_6)
        self.sb_scaling_factor.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_scaling_factor.sizePolicy().hasHeightForWidth())
        self.sb_scaling_factor.setSizePolicy(sizePolicy)
        self.sb_scaling_factor.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.sb_scaling_factor.setMinimum(2)
        self.sb_scaling_factor.setMaximum(16)
        self.sb_scaling_factor.setSingleStep(2)
        self.sb_scaling_factor.setProperty("value", 2)
        self.sb_scaling_factor.setObjectName("sb_scaling_factor")
        self.horizontalLayout_9.addWidget(self.sb_scaling_factor)
        self.gridLayout_7.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.cb_remove_edges = QtWidgets.QCheckBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_remove_edges.sizePolicy().hasHeightForWidth())
        self.cb_remove_edges.setSizePolicy(sizePolicy)
        self.cb_remove_edges.setObjectName("cb_remove_edges")
        self.gridLayout_7.addWidget(self.cb_remove_edges, 0, 0, 1, 1)
        self.gridLayout_31.addWidget(self.frame_6, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_31.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_31.addItem(spacerItem1, 3, 0, 1, 1)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 299, 462))
        self.page_2.setObjectName("page_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.page_2)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.groupBox_9 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cb_log = QtWidgets.QCheckBox(self.groupBox_9)
        self.cb_log.setStyleSheet("")
        self.cb_log.setChecked(False)
        self.cb_log.setObjectName("cb_log")
        self.horizontalLayout_7.addWidget(self.cb_log)
        self.cb_norm = QtWidgets.QCheckBox(self.groupBox_9)
        self.cb_norm.setObjectName("cb_norm")
        self.horizontalLayout_7.addWidget(self.cb_norm)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.cb_transpose = QtWidgets.QCheckBox(self.groupBox_9)
        self.cb_transpose.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_transpose.setObjectName("cb_transpose")
        self.verticalLayout_3.addWidget(self.cb_transpose)
        self.gridLayout_24.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_27.addWidget(self.groupBox_9, 0, 0, 1, 1)
        self.gridLayout_28.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.groupBox)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.cb_remove_outliers = QtWidgets.QCheckBox(self.frame_4)
        self.cb_remove_outliers.setObjectName("cb_remove_outliers")
        self.gridLayout_21.addWidget(self.cb_remove_outliers, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hs_nsigma = QtWidgets.QSlider(self.frame_4)
        self.hs_nsigma.setEnabled(False)
        self.hs_nsigma.setStyleSheet("border-color: rgb(0, 85, 255);")
        self.hs_nsigma.setMaximum(200)
        self.hs_nsigma.setProperty("value", 3)
        self.hs_nsigma.setOrientation(QtCore.Qt.Horizontal)
        self.hs_nsigma.setObjectName("hs_nsigma")
        self.horizontalLayout.addWidget(self.hs_nsigma)
        self.label_nsigma = QtWidgets.QLabel(self.frame_4)
        self.label_nsigma.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_nsigma.setObjectName("label_nsigma")
        self.horizontalLayout.addWidget(self.label_nsigma)
        self.gridLayout_21.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        self.gridLayout_28.addWidget(self.frame_4, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.groupBox)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cb_remove_bg = QtWidgets.QCheckBox(self.frame_3)
        self.cb_remove_bg.setObjectName("cb_remove_bg")
        self.horizontalLayout_3.addWidget(self.cb_remove_bg)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hs_bg_threshold = QtWidgets.QSlider(self.frame_3)
        self.hs_bg_threshold.setEnabled(False)
        self.hs_bg_threshold.setMaximum(100)
        self.hs_bg_threshold.setSingleStep(5)
        self.hs_bg_threshold.setPageStep(5)
        self.hs_bg_threshold.setProperty("value", 5)
        self.hs_bg_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.hs_bg_threshold.setObjectName("hs_bg_threshold")
        self.horizontalLayout_2.addWidget(self.hs_bg_threshold)
        self.label_bg_threshold = QtWidgets.QLabel(self.frame_3)
        self.label_bg_threshold.setObjectName("label_bg_threshold")
        self.horizontalLayout_2.addWidget(self.label_bg_threshold)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_28.addWidget(self.frame_3, 2, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cb_smooth = QtWidgets.QCheckBox(self.frame_2)
        self.cb_smooth.setObjectName("cb_smooth")
        self.gridLayout_3.addWidget(self.cb_smooth, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.hs_smooth_size = QtWidgets.QSlider(self.frame_2)
        self.hs_smooth_size.setEnabled(False)
        self.hs_smooth_size.setMinimum(3)
        self.hs_smooth_size.setMaximum(12)
        self.hs_smooth_size.setSingleStep(2)
        self.hs_smooth_size.setPageStep(2)
        self.hs_smooth_size.setProperty("value", 3)
        self.hs_smooth_size.setOrientation(QtCore.Qt.Horizontal)
        self.hs_smooth_size.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hs_smooth_size.setTickInterval(2)
        self.hs_smooth_size.setObjectName("hs_smooth_size")
        self.horizontalLayout_4.addWidget(self.hs_smooth_size)
        self.smooth_winow_size = QtWidgets.QLabel(self.frame_2)
        self.smooth_winow_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.smooth_winow_size.setObjectName("smooth_winow_size")
        self.horizontalLayout_4.addWidget(self.smooth_winow_size)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.gridLayout_28.addWidget(self.frame_2, 3, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_2, "")
        self.gridLayout_9.addWidget(self.toolBox, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem2, 2, 0, 1, 1)
        self.toolBox_2 = QtWidgets.QToolBox(self.scrollAreaWidgetContents)
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 298, 189))
        self.page_5.setObjectName("page_5")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pb_calc_components = QtWidgets.QPushButton(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_calc_components.sizePolicy().hasHeightForWidth())
        self.pb_calc_components.setSizePolicy(sizePolicy)
        self.pb_calc_components.setStyleSheet("background-color: rgb(175, 236, 255);\n"
"color: rgb(255, 0, 127);\n"
"")
        self.pb_calc_components.setObjectName("pb_calc_components")
        self.gridLayout.addWidget(self.pb_calc_components, 0, 0, 1, 1)
        self.pb_pca_scree = QtWidgets.QPushButton(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_pca_scree.sizePolicy().hasHeightForWidth())
        self.pb_pca_scree.setSizePolicy(sizePolicy)
        self.pb_pca_scree.setStyleSheet("background-color: rgb(175, 236, 255);\n"
"color: rgb(255, 0, 127);\n"
"")
        self.pb_pca_scree.setObjectName("pb_pca_scree")
        self.gridLayout.addWidget(self.pb_pca_scree, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.page_5)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.cb_comp_method = QtWidgets.QComboBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_comp_method.sizePolicy().hasHeightForWidth())
        self.cb_comp_method.setSizePolicy(sizePolicy)
        self.cb_comp_method.setObjectName("cb_comp_method")
        self.cb_comp_method.addItem("")
        self.cb_comp_method.addItem("")
        self.cb_comp_method.addItem("")
        self.cb_comp_method.addItem("")
        self.cb_comp_method.addItem("")
        self.cb_comp_method.addItem("")
        self.cb_comp_method.addItem("")
        self.horizontalLayout_5.addWidget(self.cb_comp_method)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.page_5)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.sb_ncomp = QtWidgets.QSpinBox(self.page_5)
        self.sb_ncomp.setMinimum(1)
        self.sb_ncomp.setProperty("value", 4)
        self.sb_ncomp.setObjectName("sb_ncomp")
        self.horizontalLayout_6.addWidget(self.sb_ncomp)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.toolBox_2.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 308, 185))
        self.page_6.setObjectName("page_6")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pb_calc_cluster = QtWidgets.QPushButton(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_calc_cluster.sizePolicy().hasHeightForWidth())
        self.pb_calc_cluster.setSizePolicy(sizePolicy)
        self.pb_calc_cluster.setStyleSheet("background-color: rgb(175, 236, 255);\n"
"color: rgb(255, 0, 127);\n"
"")
        self.pb_calc_cluster.setObjectName("pb_calc_cluster")
        self.gridLayout_4.addWidget(self.pb_calc_cluster, 0, 0, 1, 3)
        self.pb_kmeans_elbow = QtWidgets.QPushButton(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_kmeans_elbow.sizePolicy().hasHeightForWidth())
        self.pb_kmeans_elbow.setSizePolicy(sizePolicy)
        self.pb_kmeans_elbow.setStyleSheet("background-color: rgb(175, 236, 255);\n"
"color: rgb(255, 0, 127);\n"
"")
        self.pb_kmeans_elbow.setObjectName("pb_kmeans_elbow")
        self.gridLayout_4.addWidget(self.pb_kmeans_elbow, 1, 0, 1, 3)
        self.label_10 = QtWidgets.QLabel(self.page_6)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.cb_clust_method = QtWidgets.QComboBox(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_clust_method.sizePolicy().hasHeightForWidth())
        self.cb_clust_method.setSizePolicy(sizePolicy)
        self.cb_clust_method.setObjectName("cb_clust_method")
        self.cb_clust_method.addItem("")
        self.cb_clust_method.addItem("")
        self.cb_clust_method.addItem("")
        self.cb_clust_method.addItem("")
        self.cb_clust_method.addItem("")
        self.cb_clust_method.addItem("")
        self.gridLayout_4.addWidget(self.cb_clust_method, 2, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.page_6)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 0, 1, 2)
        self.sb_ncluster = QtWidgets.QSpinBox(self.page_6)
        self.sb_ncluster.setMinimum(1)
        self.sb_ncluster.setProperty("value", 4)
        self.sb_ncluster.setObjectName("sb_ncluster")
        self.gridLayout_4.addWidget(self.sb_ncluster, 3, 2, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.toolBox_2.addItem(self.page_6, "")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 299, 156))
        self.page_7.setObjectName("page_7")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pb_elist_xanes = QtWidgets.QPushButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_elist_xanes.sizePolicy().hasHeightForWidth())
        self.pb_elist_xanes.setSizePolicy(sizePolicy)
        self.pb_elist_xanes.setStyleSheet("background-color: rgb(175, 236, 255);\n"
"color: rgb(255, 0, 127);\n"
"")
        self.pb_elist_xanes.setObjectName("pb_elist_xanes")
        self.gridLayout_2.addWidget(self.pb_elist_xanes, 0, 0, 1, 2)
        self.cb_kev_flag = QtWidgets.QCheckBox(self.page_7)
        self.cb_kev_flag.setObjectName("cb_kev_flag")
        self.gridLayout_2.addWidget(self.cb_kev_flag, 0, 2, 1, 1)
        self.pb_ref_xanes = QtWidgets.QPushButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_ref_xanes.sizePolicy().hasHeightForWidth())
        self.pb_ref_xanes.setSizePolicy(sizePolicy)
        self.pb_ref_xanes.setStyleSheet("background-color: rgb(175, 236, 255);\n"
"color: rgb(255, 0, 127);\n"
"")
        self.pb_ref_xanes.setObjectName("pb_ref_xanes")
        self.gridLayout_2.addWidget(self.pb_ref_xanes, 1, 0, 1, 2)
        self.pb_plot_refs = QtWidgets.QPushButton(self.page_7)
        self.pb_plot_refs.setStyleSheet("background-color: rgb(175, 236, 255);\n"
"color: rgb(255, 0, 127);")
        self.pb_plot_refs.setObjectName("pb_plot_refs")
        self.gridLayout_2.addWidget(self.pb_plot_refs, 1, 2, 1, 1)
        self.cb_xanes_fitting_method = QtWidgets.QComboBox(self.page_7)
        self.cb_xanes_fitting_method.setObjectName("cb_xanes_fitting_method")
        self.cb_xanes_fitting_method.addItem("")
        self.gridLayout_2.addWidget(self.cb_xanes_fitting_method, 2, 0, 1, 1)
        self.pb_xanes_fit = QtWidgets.QPushButton(self.page_7)
        self.pb_xanes_fit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_xanes_fit.sizePolicy().hasHeightForWidth())
        self.pb_xanes_fit.setSizePolicy(sizePolicy)
        self.pb_xanes_fit.setStyleSheet("background-color: rgb(175, 236, 255);\n"
"color: rgb(255, 0, 127);\n"
"")
        self.pb_xanes_fit.setObjectName("pb_xanes_fit")
        self.gridLayout_2.addWidget(self.pb_xanes_fit, 2, 1, 1, 2)
        self.gridLayout_20.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem3, 1, 0, 1, 1)
        self.toolBox_2.addItem(self.page_7, "")
        self.gridLayout_9.addWidget(self.toolBox_2, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_16.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setStyleSheet("font:12pt \"Segoe UI\";")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.frame_5 = QtWidgets.QFrame(self.groupBox_6)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_8.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.le_spec_roi_size = QtWidgets.QLabel(self.groupBox_5)
        self.le_spec_roi_size.setStyleSheet("color: rgb(255, 0,0);")
        self.le_spec_roi_size.setObjectName("le_spec_roi_size")
        self.gridLayout_11.addWidget(self.le_spec_roi_size, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setStyleSheet("")
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_11.addWidget(self.label_29, 1, 0, 1, 1)
        self.le_spec_roi = QtWidgets.QLabel(self.groupBox_5)
        self.le_spec_roi.setStyleSheet("color: rgb(255, 0,0);")
        self.le_spec_roi.setObjectName("le_spec_roi")
        self.gridLayout_11.addWidget(self.le_spec_roi, 0, 1, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_12.addWidget(self.label_4, 0, 0, 1, 1)
        self.le_roi = QtWidgets.QLabel(self.groupBox_4)
        self.le_roi.setStyleSheet("color: rgb(255, 0,0);")
        self.le_roi.setObjectName("le_roi")
        self.gridLayout_12.addWidget(self.le_roi, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setStyleSheet("")
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_12.addWidget(self.label_28, 1, 0, 1, 1)
        self.le_roi_size = QtWidgets.QLabel(self.groupBox_4)
        self.le_roi_size.setStyleSheet("color: rgb(255, 0, 0);")
        self.le_roi_size.setObjectName("le_roi_size")
        self.gridLayout_12.addWidget(self.le_roi_size, 1, 1, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.rb_math_roi_img = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb_math_roi_img.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rb_math_roi_img.setObjectName("rb_math_roi_img")
        self.gridLayout_6.addWidget(self.rb_math_roi_img, 0, 0, 1, 1)
        self.pb_reset_roi_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_reset_roi_2.setStyleSheet("background-color: rgb(175, 236, 255);")
        self.pb_reset_roi_2.setObjectName("pb_reset_roi_2")
        self.gridLayout_6.addWidget(self.pb_reset_roi_2, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 1, 0, 1, 1)
        self.cb_img_roi_action = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_img_roi_action.sizePolicy().hasHeightForWidth())
        self.cb_img_roi_action.setSizePolicy(sizePolicy)
        self.cb_img_roi_action.setObjectName("cb_img_roi_action")
        self.cb_img_roi_action.addItem("")
        self.cb_img_roi_action.addItem("")
        self.cb_img_roi_action.addItem("")
        self.cb_img_roi_action.addItem("")
        self.gridLayout_6.addWidget(self.cb_img_roi_action, 1, 1, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.rb_math_roi = QtWidgets.QRadioButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_math_roi.sizePolicy().hasHeightForWidth())
        self.rb_math_roi.setSizePolicy(sizePolicy)
        self.rb_math_roi.setCheckable(True)
        self.rb_math_roi.setChecked(False)
        self.rb_math_roi.setObjectName("rb_math_roi")
        self.gridLayout_14.addWidget(self.rb_math_roi, 0, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_14.addWidget(self.label_13, 1, 0, 1, 1)
        self.cb_roi_operation = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_roi_operation.sizePolicy().hasHeightForWidth())
        self.cb_roi_operation.setSizePolicy(sizePolicy)
        self.cb_roi_operation.setObjectName("cb_roi_operation")
        self.cb_roi_operation.addItem("")
        self.cb_roi_operation.addItem("")
        self.cb_roi_operation.addItem("")
        self.cb_roi_operation.addItem("")
        self.gridLayout_14.addWidget(self.cb_roi_operation, 1, 1, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_7, 10, 0, 1, 1)
        self.pb_save_disp_img = QtWidgets.QPushButton(self.frame_5)
        self.pb_save_disp_img.setStyleSheet("background-color: rgb(175, 236, 255);\n"
"color: rgb(255, 0, 127);")
        self.pb_save_disp_img.setObjectName("pb_save_disp_img")
        self.gridLayout_23.addWidget(self.pb_save_disp_img, 13, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem4, 4, 0, 1, 1)
        self.pb_save_disp_spec = QtWidgets.QPushButton(self.frame_5)
        self.pb_save_disp_spec.setStyleSheet("background-color: rgb(175, 236, 255);\n"
"color: rgb(255, 0, 127);")
        self.pb_save_disp_spec.setObjectName("pb_save_disp_spec")
        self.gridLayout_23.addWidget(self.pb_save_disp_spec, 14, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem5, 12, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_poly_roi = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_poly_roi.setChecked(True)
        self.rb_poly_roi.setObjectName("rb_poly_roi")
        self.verticalLayout.addWidget(self.rb_poly_roi)
        self.rb_rect_roi = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_rect_roi.setObjectName("rb_rect_roi")
        self.verticalLayout.addWidget(self.rb_rect_roi)
        self.gridLayout_22.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rb_elli_roi = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_elli_roi.setObjectName("rb_elli_roi")
        self.verticalLayout_2.addWidget(self.rb_elli_roi)
        self.rb_circle_roi = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_circle_roi.setObjectName("rb_circle_roi")
        self.verticalLayout_2.addWidget(self.rb_circle_roi)
        self.gridLayout_22.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.rb_line_roi = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_line_roi.setObjectName("rb_line_roi")
        self.gridLayout_22.addWidget(self.rb_line_roi, 1, 0, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_2, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem6, 2, 0, 1, 1)
        self.gridLayout_29.addWidget(self.frame_5, 0, 2, 2, 1)
        self.image_view = ImageView(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_view.sizePolicy().hasHeightForWidth())
        self.image_view.setSizePolicy(sizePolicy)
        self.image_view.setObjectName("image_view")
        self.gridLayout_29.addWidget(self.image_view, 0, 1, 1, 1)
        self.spectrum_view = PlotWidget(self.groupBox_6)
        self.spectrum_view.setObjectName("spectrum_view")
        self.gridLayout_29.addWidget(self.spectrum_view, 1, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_6, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1246, 29))
        self.menubar.setObjectName("menubar")
        self.menuManual = QtWidgets.QMenu(self.menubar)
        self.menuManual.setObjectName("menuManual")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuMask = QtWidgets.QMenu(self.menubar)
        self.menuMask.setObjectName("menuMask")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar_main = QtWidgets.QStatusBar(MainWindow)
        self.statusbar_main.setObjectName("statusbar_main")
        MainWindow.setStatusBar(self.statusbar_main)
        self.actionOpen_PDF = QtWidgets.QAction(MainWindow)
        self.actionOpen_PDF.setObjectName("actionOpen_PDF")
        self.actionOpen_in_GitHub = QtWidgets.QAction(MainWindow)
        self.actionOpen_in_GitHub.setObjectName("actionOpen_in_GitHub")
        self.actionOpen_Image_Data = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image_Data.setEnabled(True)
        self.actionOpen_Image_Data.setObjectName("actionOpen_Image_Data")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionOpen_PyXRF = QtWidgets.QAction(MainWindow)
        self.actionOpen_PyXRF.setObjectName("actionOpen_PyXRF")
        self.actionOpen_Image_J = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image_J.setObjectName("actionOpen_Image_J")
        self.actionOpen_TomViz = QtWidgets.QAction(MainWindow)
        self.actionOpen_TomViz.setObjectName("actionOpen_TomViz")
        self.actionOpen_Mantis = QtWidgets.QAction(MainWindow)
        self.actionOpen_Mantis.setObjectName("actionOpen_Mantis")
        self.actionOpen_Athena = QtWidgets.QAction(MainWindow)
        self.actionOpen_Athena.setObjectName("actionOpen_Athena")
        self.actionDataBroker = QtWidgets.QAction(MainWindow)
        self.actionDataBroker.setObjectName("actionDataBroker")
        self.actionOpen_HXN_DB = QtWidgets.QAction(MainWindow)
        self.actionOpen_HXN_DB.setObjectName("actionOpen_HXN_DB")
        self.actionLoad_Energy = QtWidgets.QAction(MainWindow)
        self.actionLoad_Energy.setObjectName("actionLoad_Energy")
        self.actionOpen_Multiple_Files = QtWidgets.QAction(MainWindow)
        self.actionOpen_Multiple_Files.setObjectName("actionOpen_Multiple_Files")
        self.actionOpen_Mask_Gen = QtWidgets.QAction(MainWindow)
        self.actionOpen_Mask_Gen.setObjectName("actionOpen_Mask_Gen")
        self.actionCreate_elist_from_log = QtWidgets.QAction(MainWindow)
        self.actionCreate_elist_from_log.setObjectName("actionCreate_elist_from_log")
        self.actionSave_Energy_List = QtWidgets.QAction(MainWindow)
        self.actionSave_Energy_List.setObjectName("actionSave_Energy_List")
        self.actionAlign_Stack = QtWidgets.QAction(MainWindow)
        self.actionAlign_Stack.setObjectName("actionAlign_Stack")
        self.menuManual.addSeparator()
        self.menuManual.addAction(self.actionOpen_in_GitHub)
        self.menuFile.addAction(self.actionOpen_Image_Data)
        self.menuFile.addAction(self.actionOpen_Multiple_Files)
        self.menuFile.addAction(self.actionLoad_Energy)
        self.menuFile.addAction(self.actionSave_Energy_List)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExit)
        self.menuMask.addAction(self.actionOpen_Mask_Gen)
        self.menuMask.addAction(self.actionAlign_Stack)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMask.menuAction())
        self.menubar.addAction(self.menuManual.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        self.toolBox_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NSLS-II MIDAS"))
        self.pb_reset_img.setText(_translate("MainWindow", "Reset Image"))
        self.label_5.setText(_translate("MainWindow", "to"))
        self.label_9.setText(_translate("MainWindow", "to"))
        self.sb_yrange2.setSuffix(_translate("MainWindow", " px"))
        self.sb_xrange1.setSuffix(_translate("MainWindow", " px"))
        self.sb_xrange2.setSuffix(_translate("MainWindow", " px"))
        self.label_22.setText(_translate("MainWindow", "to"))
        self.label_19.setText(_translate("MainWindow", "X Dimension"))
        self.sb_yrange1.setSuffix(_translate("MainWindow", " px"))
        self.label_15.setText(_translate("MainWindow", "Y Dimension"))
        self.label_20.setText(_translate("MainWindow", "Stack Range "))
        self.pb_crop.setToolTip(_translate("MainWindow", "Adjust the dimensions of the image"))
        self.pb_crop.setText(_translate("MainWindow", "Update"))
        self.cb_rebin.setText(_translate("MainWindow", "rebin"))
        self.cb_upscale.setText(_translate("MainWindow", "Upscale"))
        self.cb_remove_edges.setToolTip(_translate("MainWindow", "Removes one column/row from all four edges"))
        self.cb_remove_edges.setText(_translate("MainWindow", "Remove Edges"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Adjust Image Dimensions"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Transform"))
        self.cb_log.setToolTip(_translate("MainWindow", "Covert image dat to log values."))
        self.cb_log.setText(_translate("MainWindow", "Log "))
        self.cb_norm.setToolTip(_translate("MainWindow", "Intensity Normalization with the last Frame."))
        self.cb_norm.setText(_translate("MainWindow", "Normalize"))
        self.cb_transpose.setToolTip(_translate("MainWindow", "Reverse the arrays. 012 will be 210"))
        self.cb_transpose.setText(_translate("MainWindow", "Transpose"))
        self.cb_remove_outliers.setText(_translate("MainWindow", "Remove Outliers (NSigma)"))
        self.label_nsigma.setText(_translate("MainWindow", "1"))
        self.cb_remove_bg.setText(_translate("MainWindow", "Thresholding"))
        self.label_bg_threshold.setText(_translate("MainWindow", "5"))
        self.cb_smooth.setToolTip(_translate("MainWindow", "uses savgol_filter to smooth data"))
        self.cb_smooth.setText(_translate("MainWindow", "Smoothen"))
        self.smooth_winow_size.setText(_translate("MainWindow", "Window size"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Image Processing"))
        self.pb_calc_components.setText(_translate("MainWindow", "Calculate Components"))
        self.pb_pca_scree.setText(_translate("MainWindow", "PCA Scree Plot"))
        self.label_11.setText(_translate("MainWindow", "Method"))
        self.cb_comp_method.setItemText(0, _translate("MainWindow", "PCA"))
        self.cb_comp_method.setItemText(1, _translate("MainWindow", "NMF"))
        self.cb_comp_method.setItemText(2, _translate("MainWindow", "FastICA"))
        self.cb_comp_method.setItemText(3, _translate("MainWindow", "IncrementalPCA"))
        self.cb_comp_method.setItemText(4, _translate("MainWindow", "TruncatedSVD"))
        self.cb_comp_method.setItemText(5, _translate("MainWindow", "FactorAnalysis"))
        self.cb_comp_method.setItemText(6, _translate("MainWindow", "DictionaryLearning"))
        self.label.setText(_translate("MainWindow", "Number of Components"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_5), _translate("MainWindow", "Component Analysis"))
        self.pb_calc_cluster.setText(_translate("MainWindow", "Calculate Clusters"))
        self.pb_kmeans_elbow.setText(_translate("MainWindow", "KMeans Variance Plot"))
        self.label_10.setText(_translate("MainWindow", "Method"))
        self.cb_clust_method.setItemText(0, _translate("MainWindow", "KMeans"))
        self.cb_clust_method.setItemText(1, _translate("MainWindow", "MiniBatchKMeans"))
        self.cb_clust_method.setItemText(2, _translate("MainWindow", "MeanShift"))
        self.cb_clust_method.setItemText(3, _translate("MainWindow", "Spectral Clustering"))
        self.cb_clust_method.setItemText(4, _translate("MainWindow", "Correlation-Kmeans"))
        self.cb_clust_method.setItemText(5, _translate("MainWindow", "Affinity Propagation"))
        self.label_2.setText(_translate("MainWindow", "Number of Clusters"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_6), _translate("MainWindow", "Cluster Analysis"))
        self.pb_elist_xanes.setText(_translate("MainWindow", "Load Energy List"))
        self.cb_kev_flag.setText(_translate("MainWindow", "keV"))
        self.pb_ref_xanes.setText(_translate("MainWindow", "Load Ref. Spec."))
        self.pb_plot_refs.setText(_translate("MainWindow", "Plot"))
        self.cb_xanes_fitting_method.setItemText(0, _translate("MainWindow", "NNLS"))
        self.pb_xanes_fit.setText(_translate("MainWindow", " Fit"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_7), _translate("MainWindow", "XANES Fitting"))
        self.groupBox_8.setTitle(_translate("MainWindow", "ROI Positions"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Spectrum ROI"))
        self.le_spec_roi_size.setText(_translate("MainWindow", "roi_size"))
        self.label_8.setText(_translate("MainWindow", "Range (eV):"))
        self.label_29.setText(_translate("MainWindow", "Size (eV):"))
        self.le_spec_roi.setText(_translate("MainWindow", "roix, roiy"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Image ROI"))
        self.label_4.setText(_translate("MainWindow", "Position:"))
        self.le_roi.setText(_translate("MainWindow", "roix, roiy"))
        self.label_28.setText(_translate("MainWindow", "Size(pixels):"))
        self.le_roi_size.setText(_translate("MainWindow", "roi_size"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Image Calculations"))
        self.rb_math_roi_img.setText(_translate("MainWindow", "Add Math ROI"))
        self.pb_reset_roi_2.setText(_translate("MainWindow", "Reset"))
        self.label_14.setText(_translate("MainWindow", "Action:"))
        self.cb_img_roi_action.setItemText(0, _translate("MainWindow", "Subtract"))
        self.cb_img_roi_action.setItemText(1, _translate("MainWindow", "Divide"))
        self.cb_img_roi_action.setItemText(2, _translate("MainWindow", "Add"))
        self.cb_img_roi_action.setItemText(3, _translate("MainWindow", "Compare"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Spectrum Calculations"))
        self.rb_math_roi.setText(_translate("MainWindow", "Add Math ROI"))
        self.label_13.setText(_translate("MainWindow", "Action:"))
        self.cb_roi_operation.setItemText(0, _translate("MainWindow", "Divide"))
        self.cb_roi_operation.setItemText(1, _translate("MainWindow", "Subtract"))
        self.cb_roi_operation.setItemText(2, _translate("MainWindow", "Add"))
        self.cb_roi_operation.setItemText(3, _translate("MainWindow", "Correlation Plot"))
        self.pb_save_disp_img.setText(_translate("MainWindow", "Save Current Image (.tiff)"))
        self.pb_save_disp_spec.setText(_translate("MainWindow", "Save Current Spectrum (.txt)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "ROI Shape"))
        self.rb_poly_roi.setText(_translate("MainWindow", "Polygon (default)"))
        self.rb_rect_roi.setText(_translate("MainWindow", "Rectangle"))
        self.rb_elli_roi.setText(_translate("MainWindow", "Ellipse"))
        self.rb_circle_roi.setText(_translate("MainWindow", "Circle"))
        self.rb_line_roi.setText(_translate("MainWindow", "Line"))
        self.menuManual.setTitle(_translate("MainWindow", "Help"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuMask.setTitle(_translate("MainWindow", "Tools"))
        self.actionOpen_PDF.setText(_translate("MainWindow", "Open PDF"))
        self.actionOpen_in_GitHub.setText(_translate("MainWindow", "Open in GitHub (most updated)"))
        self.actionOpen_Image_Data.setText(_translate("MainWindow", "Open Image Data"))
        self.actionOpen_Image_Data.setToolTip(_translate("MainWindow", "Support all tiff and specific h5 files"))
        self.actionOpen_Image_Data.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSave_as.setText(_translate("MainWindow", "Export Tiff Stack"))
        self.actionSave_as.setToolTip(_translate("MainWindow", "Save the displayed/Modified stack as a tiff file"))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen_PyXRF.setText(_translate("MainWindow", "Open PyXRF"))
        self.actionOpen_Image_J.setText(_translate("MainWindow", "Open Image J"))
        self.actionOpen_TomViz.setText(_translate("MainWindow", "Open TomViz"))
        self.actionOpen_Mantis.setText(_translate("MainWindow", "Open Mantis"))
        self.actionOpen_Athena.setText(_translate("MainWindow", "Open Athena"))
        self.actionDataBroker.setText(_translate("MainWindow", "DataBroker"))
        self.actionOpen_HXN_DB.setText(_translate("MainWindow", "Open HXN DB"))
        self.actionLoad_Energy.setText(_translate("MainWindow", "Load Energy"))
        self.actionLoad_Energy.setToolTip(_translate("MainWindow", "Load list of energies for XANES stack. Supports only .txt fromat"))
        self.actionLoad_Energy.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionOpen_Multiple_Files.setText(_translate("MainWindow", "Open Multiple Files"))
        self.actionOpen_Multiple_Files.setToolTip(_translate("MainWindow", "Create a stack from multiple tiff images of same shape"))
        self.actionOpen_Multiple_Files.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionOpen_Mask_Gen.setText(_translate("MainWindow", "Open Mask Generator"))
        self.actionOpen_Mask_Gen.setToolTip(_translate("MainWindow", "A new window will be opened to creat threshold based masks"))
        self.actionCreate_elist_from_log.setText(_translate("MainWindow", "Create elist from log file"))
        self.actionSave_Energy_List.setText(_translate("MainWindow", "Save Energy List"))
        self.actionAlign_Stack.setText(_translate("MainWindow", "Align Stack"))
        self.actionAlign_Stack.setToolTip(_translate("MainWindow", "A new window will be opened to align images in a stack"))
from pyqtgraph import ImageView, PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
